package org.bamboo.model.flightport;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "flight", targetNamespace = "http://www.ibsplc.com/wsdl", wsdlLocation = "https://iflyrestest.ibsgen.com:6143/iRes_Booking_WS/services/FlightPort?wsdl")
public class Flight
        extends Service {

    private final static URL FLIGHT_WSDL_LOCATION;
    private final static WebServiceException FLIGHT_EXCEPTION;
    private final static QName FLIGHT_QNAME = new QName("http://www.ibsplc.com/wsdl", "flight");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://iflyrestest.ibsgen.com:6143/iRes_Booking_WS/services/FlightPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHT_WSDL_LOCATION = url;
        FLIGHT_EXCEPTION = e;
    }

    public Flight() {
        super(__getWsdlLocation(), FLIGHT_QNAME);
    }

    public Flight(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHT_QNAME, features);
    }

    public Flight(URL wsdlLocation) {
        super(wsdlLocation, FLIGHT_QNAME);
    }

    public Flight(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHT_QNAME, features);
    }

    public Flight(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Flight(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns FlightPort
     */
    @WebEndpoint(name = "FlightPort")
    public FlightPort getFlightPort() {
        return super.getPort(new QName("http://www.ibsplc.com/wsdl", "FlightPort"), FlightPort.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns FlightPort
     */
    @WebEndpoint(name = "FlightPort")
    public FlightPort getFlightPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibsplc.com/wsdl", "FlightPort"), FlightPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHT_EXCEPTION != null) {
            throw FLIGHT_EXCEPTION;
        }
        return FLIGHT_WSDL_LOCATION;
    }

}
